---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

suites:
  - name: client
    run_list:
      - recipe[zookeeperd]
  - name: server
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        config:
          client_port: 9000
