---
driver:
  name: vagrant
  customize:
    memory: 1048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: client
    run_list:
      - recipe[zookeeperd]
  - name: server
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        cluster:
          auto_discovery: false
        config:
          client_port: 9000
  - name: server-cloudera
    includes:
      - ubuntu-12.04
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        cluster:
          auto_discovery: false
        config:
          client_port: 9000
        cloudera_repo: true
